import Head from "next/head";
import { Inter } from "next/font/google";
import { AnimeList, Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

const AnimeListPage = () => {
  return (
    <>
      <Head>
        <title>Anime Collections App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={`${inter.className}`}>
        <Header />
        <AnimeList />
      </main>
    </>
  );
};

export default AnimeListPage;
